### PR TITLE
data attribute to disable date picker

### PR DESCRIPTION
**Pull request by brewster1134**
we were looking at ways to use native date input behavior on a per input/form basis. how do you feel about a simple check if an input is explicitly disabled?

```html
<input type="date" data-dateinput-disabled></input>
```

### CODE REVIEW

**Comment by brewster1134** [comment]
@chemerisuk bump? thoughts?

**Comment by chemerisuk** [comment]
@brewster1134 sorry for a late reply. The polyfill already has ability to enable/disable default browser behavior. Please read https://github.com/chemerisuk/better-dateinput-polyfill#forcing-the-polyfill

**Comment by brewster1134** [comment]
is it possible to force native for both mobile AND desktop? this was the issue I was facing

**Comment by chemerisuk** [comment]
It is not possible for now, and I guess it's useless... What use case do you have?

Anyway you could add such feature by adding extra check `if (nativeValue === "all") return false;` before https://github.com/chemerisuk/better-dateinput-polyfill/blob/master/dist/better-dateinput-polyfill.js#L335

**Comment by brewster1134** [comment]
we have a birthday field and going back 30 or so years is a bit cumbersome with the datepicker, but we want other date fields (chosing a callback time) in the same form to use the datepicker.

if you would be interested in merging it, i can update the PR to use the existing `data-native` attribute

**Comment by chemerisuk** [comment]
@brewster1134 okay, I got your case. As for the PR - the best way will be for you to make a fork and add the line above into `dist/better-dateinput-polyfill.js` directly. The issue is that I've started working on the next version already. It will introduce some breaking changes and unfortunately I don't have any estimates yet when it will be published.

**Comment by brewster1134** [comment]
do you mean for purposes of meeting my needs? or for eventual merging into your codebase?  I have been using my fork already, but if you are working on a new version, perhaps I should just keep using my fork for now, and when you have your new version ready, we can look at integrating this feature into the new version?  I dont want to invest too much time in a feature for a version that will soon be sunsetting :wink: 

Let me know what you think!

**Comment by chemerisuk** [comment]
@brewster1134 yep, keep those changes in your fork for now. I'll ping you when a new version will be ready for the contribution.

**Comment by chemerisuk** [comment]
Fixed in https://github.com/chemerisuk/better-dateinput-polyfill/commit/f93d29022df4d16fe4fa6c0e722bcb7b92392ce0.

**Pull request closed without merging**
