### PR TITLE
Added Galician (gl) language

### PR DESCRIPTION
**Pull request by bertez**
Just added [Galician languange](http://en.wikipedia.org/wiki/Galician_language)

Cheers!

### CODE REVIEW

**Comment by chemerisuk** [comment]
@bertez thank you! Do you really use the dot suffix for compact months?

**Comment by bertez** [comment]
Hi, @chemerisuk 

for compact days in the header of the calendar we do not use dot suffix, we know that kind of abbreviations as _two-letter codes_.

But the standard rule in our language is to use dot suffix for every abbreviation and I understood that the use of compact months in the date picker are more like an standard abbreviation than a three-letter code.

Anyway, both ways should be ok. So I will update the pull request to remove the dot suffix for the sake of economy of language :smile:

**Comment by chemerisuk** [comment]
@bertez you still have 2 strings with dots left: `"Nov."`, `"Dec."`

**Comment by bertez** [comment]
Sorry about that, fixed now.

**Comment by chemerisuk** [comment]
@bertez alright, looks good

**Comment by bertez** [comment]
Thank you!

**Pull request merged**
